name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NEXT_PUBLIC_BACKEND_URL: ${{secrets.NEXT_PUBLIC_BACKEND_URL}}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build # Additionally creates a file telling Github not to build the project using Jekyll
        run: |
          yarn
          yarn build
          touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages 
          folder: out